//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int code { get; set; }
        public string name { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<int> deptid { get; set; }
    }
}
